version: '3'

services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - .env

    ports:
      - "5432:5432"

  redis:
    restart: always
    image: "redis:alpine"
    expose:
    - "6379"
